# Generated by Django 6.0.7 on 2026-07-11 19:55

import apps.profiles.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='catalog.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_parent',
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.tutor_photo_path)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to=apps.profiles.models.tutor_document_path)),
                ('qualification_document', models.FileField(blank=True, null=True, upload_to=apps.profiles.models.tutor_document_path)),
                ('teaching_mode', models.CharField(choices=[('ONLINE', 'Online only'), ('OFFLINE', 'Home visit only'), ('BOTH', 'Both')], default='OFFLINE', max_length=10)),
                ('fee_type', models.CharField(choices=[('PER_HOUR', 'Per hour'), ('PER_MONTH', 'Per month')], default='PER_HOUR', max_length=10)),
                ('expected_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_accepting_students', models.BooleanField(default=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_areas', models.ManyToManyField(blank=True, related_name='tutors', to='catalog.area')),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutors', to='catalog.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutors_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_tutor',
            },
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='profiles.tutorprofile')),
            ],
            options={
                'db_table': 'profiles_tutor_availability',
            },
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['verification_status', 'is_accepting_students'], name='profiles_tu_verific_bf2598_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tutoravailability',
            unique_together={('tutor', 'weekday', 'start_time', 'end_time')},
        ),
    ]
