
# Generated by Django 5.0.14 on 2026-08-04 07:52

import apps.profiles.models
import apps.profiles.validators
import django.core.validators
from django.db import migrations, models


def rename_offline_to_home(apps, schema_editor):
    """
    TeachingMode.OFFLINE was renamed to TeachingMode.HOME (same meaning,
    clearer name now that ACADEMY exists as a third mode elsewhere in
    the schema). Existing rows still hold the literal string 'OFFLINE'
    -- rewrite them so filtering/display keeps working post-deploy.
    """
    TutorProfile = apps.get_model('profiles', 'TutorProfile')
    TutorProfile.objects.filter(teaching_mode='OFFLINE').update(teaching_mode='HOME')


def rename_home_to_offline(apps, schema_editor):
    """Reverse of rename_offline_to_home, for migrate-backwards support."""
    TutorProfile = apps.get_model('profiles', 'TutorProfile')
    TutorProfile.objects.filter(teaching_mode='HOME').update(teaching_mode='OFFLINE')


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='home_visit_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee for in-person home-visit sessions, in the unit set by fee_type.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='online_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee for online sessions, in the unit set by fee_type.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.tutor_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.profiles.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='qualification_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.profiles.models.tutor_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.profiles.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.profiles.models.tutor_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.profiles.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='teaching_mode',
            field=models.CharField(choices=[('ONLINE', 'Online only'), ('HOME', 'Home visit only'), ('BOTH', 'Both')], default='HOME', max_length=10),
        ),
        migrations.RunPython(rename_offline_to_home, rename_home_to_offline),
    ]
