# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_tutorprofile_home_visit_fee_tutorprofile_online_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='student_class',
            field=models.CharField(
                blank=True,
                choices=[
                    ('C1_5', 'Class 1\u20135'),
                    ('C6_8', 'Class 6\u20138'),
                    ('C9_10', 'Class 9\u201310'),
                    ('C11_12', 'Class 11\u201312'),
                    ('DEGREE', 'Degree'),
                    ('COMPETITIVE', 'Competitive Exam Prep'),
                ],
                help_text='Grade/level the child needs tutoring for, as given at signup.',
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='budget_fee',
            field=models.CharField(
                blank=True,
                help_text="Affordable fee the parent mentioned at signup, free text (e.g. '600/hr').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='preferred_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='preferred_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
