# Generated by Django 5.0.14 on 2026-08-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='accounts_em_user_id_766c1e_idx',
            old_name='accounts_email_otp_lookup_idx',
        ),
    ]
