# Generated by Django 6.0.7 on 2026-07-12 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('area', models.CharField(help_text='Validated against active Area names at submission time.', max_length=100)),
                ('student_class', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('preferred_timing', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted to account'), ('CLOSED', 'Closed / not proceeding')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leads_parent_lead',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'area'], name='leads_paren_status_e6079a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TutorLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('area', models.CharField(help_text='Validated against active Area names at submission time.', max_length=100)),
                ('subjects', models.CharField(blank=True, max_length=255)),
                ('classes', models.CharField(blank=True, max_length=255)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('expected_fee', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted to account'), ('CLOSED', 'Closed / not proceeding')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leads_tutor_lead',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'area'], name='leads_tutor_status_ec1e41_idx')],
            },
        ),
    ]
