# Generated by Django 5.0.14 on 2026-08-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_ai_triage_and_duplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentlead',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentlead',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentlead',
            name='consent_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tutorlead',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorlead',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorlead',
            name='consent_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
