# Generated by Django 6.0.7 on 2026-07-11 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed — awaiting demo'), ('DEMO_SCHEDULED', 'Demo scheduled'), ('DEMO_COMPLETED', 'Demo completed'), ('ACCEPTED', 'Ongoing classes'), ('DECLINED', 'Declined after demo'), ('ENDED', 'Classes ended')], default='PROPOSED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When ongoing classes began.', null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='profiles.tutorprofile')),
            ],
            options={
                'db_table': 'matching_assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No-show'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=15)),
                ('feedback_from_parent', models.TextField(blank=True)),
                ('feedback_from_tutor', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_classes', to='matching.assignment')),
            ],
            options={
                'db_table': 'matching_demo_class',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('student_class', models.CharField(choices=[('C1_5', 'Class 1–5'), ('C6_8', 'Class 6–8'), ('C9_10', 'Class 9–10'), ('C11_12', 'Class 11–12'), ('DEGREE', 'Degree'), ('COMPETITIVE', 'Competitive Exam Prep')], max_length=15)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE', 'State Board'), ('IB', 'IB'), ('OTHER', 'Other')], default='STATE', max_length=10)),
                ('teaching_mode_preference', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Home visit'), ('BOTH', 'Either')], default='OFFLINE', max_length=10)),
                ('preferred_timing', models.CharField(blank=True, max_length=150)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open — awaiting match'), ('MATCHED', 'Tutor proposed'), ('DEMO_SCHEDULED', 'Demo scheduled'), ('CONVERTED', 'Converted to ongoing classes'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled by parent')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_requests', to='catalog.area')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='profiles.parentprofile')),
                ('subjects', models.ManyToManyField(related_name='student_requests', to='catalog.subject')),
            ],
            options={
                'db_table': 'matching_student_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='matching.studentrequest'),
        ),
        migrations.AddIndex(
            model_name='studentrequest',
            index=models.Index(fields=['status', 'area'], name='matching_st_status_eca3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrequest',
            index=models.Index(fields=['created_at'], name='matching_st_created_04e358_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='matching_as_status_fd464d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('student_request', 'tutor')},
        ),
    ]
