# Generated by Django 5.0.14 on 2026-08-04 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def rename_teaching_mode_values(apps, schema_editor):
    """
    TeachingModePreference.OFFLINE -> HOME, and BOTH -> ANY (ANY also now
    means "or an academy", not just "online or home", so the old BOTH
    string shouldn't linger with its old meaning attached).
    """
    StudentRequest = apps.get_model('matching', 'StudentRequest')
    StudentRequest.objects.filter(teaching_mode_preference='OFFLINE').update(teaching_mode_preference='HOME')
    StudentRequest.objects.filter(teaching_mode_preference='BOTH').update(teaching_mode_preference='ANY')


def revert_teaching_mode_values(apps, schema_editor):
    """Reverse of rename_teaching_mode_values, for migrate-backwards support."""
    StudentRequest = apps.get_model('matching', 'StudentRequest')
    StudentRequest.objects.filter(teaching_mode_preference='HOME').update(teaching_mode_preference='OFFLINE')
    StudentRequest.objects.filter(teaching_mode_preference='ANY').update(teaching_mode_preference='BOTH')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_academy'),
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='video_class_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='democlass',
            name='video_class_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Parent consented to Tutoro processing this data per the DPDP Act.'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='consent_version',
            field=models.CharField(blank=True, help_text='Which version of the privacy notice was shown when consent was given.', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='teaching_mode_preference',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('HOME', 'Home visit'), ('ACADEMY', 'Academy / coaching institute'), ('ANY', 'Any of the above')], default='HOME', max_length=10),
        ),
        migrations.RunPython(rename_teaching_mode_values, revert_teaching_mode_values),
        migrations.CreateModel(
            name='AcademyReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REFERRED', 'Referred to academy'), ('CONTACTED', 'Academy contacted the family'), ('ENROLLED', 'Enrolled'), ('DECLINED', 'Declined / not proceeding')], default='REFERRED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='catalog.academy')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_referrals_made', to=settings.AUTH_USER_MODEL)),
                ('student_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_referrals', to='matching.studentrequest')),
            ],
            options={
                'db_table': 'matching_academy_referral',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='matching_ac_status_e7d629_idx')],
                'unique_together': {('student_request', 'academy')},
            },
        ),
    ]
