# Generated by Django 5.0.14 on 2026-08-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_assignment_video_class_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='democlass',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
