"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, True))
environ.Env.read_env(BASE_DIR / '.env')  # no-op if .env doesn't exist -- fine for local sqlite dev


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the dev key only when DJANGO_SECRET_KEY isn't set in the
# environment -- Render's render.yaml auto-generates a real one at deploy time.
_INSECURE_DEFAULT_SECRET_KEY = 'django-insecure-k&62lru*(1l*!f=g*y)c&bwmcg=mf=jqu6^iki0v@9!jzrg@0*'
SECRET_KEY = env('DJANGO_SECRET_KEY', default=_INSECURE_DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', 'testserver'])

# -----------------------------------------------------------------
# PRODUCTION SAFETY NET -- fail loud at startup rather than silently
# serving a misconfigured deploy. If DEBUG is False (i.e. this looks
# like a real production run) but the secret key is still the dev
# fallback, something is wrong with the environment (missing env var,
# wrong host, forked repo without its own .env) -- refuse to boot
# instead of running production traffic on a dev secret with unknown
# ALLOWED_HOSTS.
# -----------------------------------------------------------------
if not DEBUG and SECRET_KEY == _INSECURE_DEFAULT_SECRET_KEY:
    raise ImproperlyConfigured(
        "DEBUG=False but DJANGO_SECRET_KEY is not set in the environment. "
        "Refusing to start with the insecure default secret key in what "
        "looks like a production run. Set DJANGO_SECRET_KEY (Render does "
        "this automatically via render.yaml's generateValue: true)."
    )

# Render (and most PaaS hosts) terminate HTTPS at their proxy and forward
# to your app over plain HTTP internally. Without this, Django doesn't
# know the original request was secure, which breaks CSRF validation on
# forms like the admin login -- this is what causes "CSRF verification
# failed" even though the site is genuinely running over HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['https://*.onrender.com'])


# Application definition

AUTH_USER_MODEL = 'accounts.User'

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.accounts',
    'apps.profiles',
    'apps.catalog',
    'apps.matching',
    'apps.reviews',
    'apps.payments',
    'apps.notifications',
    'apps.audit',
    'apps.leads',
    'apps.ai',
    # django-axes -- brute-force lockout for the Django admin login page.
    # /api/auth/login/ already has its own IP-rate-limited throttle
    # (ThrottledTokenObtainPairView, see apps/accounts/views.py); admin
    # had nothing until now (Phase 0 roadmap item: "login throttling ...
    # on /api/auth/login/ AND Django admin login").
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must be the LAST middleware in the list -- axes docs require this
    # so it sees the final response/request state before deciding
    # whether to lock out. Only affects the admin login (see
    # AXES_ONLY_ADMIN_SITE below), so it doesn't interact with the
    # DRF-throttled /api/auth/login/ at all.
    'axes.middleware.AxesMiddleware',
]

# django-axes needs its backend checked before Django's default so it
# can reject already-locked-out attempts before a real auth check runs.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Which frontend origins are allowed to call this API from the browser.
# Set to your GitHub Pages URL (e.g. https://yourusername.github.io) in
# Render's environment variables -- kept empty by default so nothing is
# accidentally left wide open.
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Local dev (no .env, no DATABASE_URL set): falls back to SQLite automatically.
# Production (Render): DATABASE_URL is set to your Aiven Postgres connection
# string, and env.db() parses it into the dict Django expects.

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
# Don't hard-crash the whole page with a 500 if one static file reference
# doesn't perfectly match the manifest (can happen after a partial
# rebuild or timing quirk between build and deploy on Render) -- fall
# back to serving it unhashed instead of raising.
WHITENOISE_MANIFEST_STRICT = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------------------------------------------
# PRODUCTION SECURITY HEADERS -- only active when DEBUG=False (Render),
# never interferes with local development.
# -----------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Without this, Django's default logging only mails 500-error tracebacks
# to ADMINS (which we haven't configured) when DEBUG=False -- meaning
# every server error becomes genuinely invisible in Render's logs, not
# just hidden from the browser. This makes tracebacks print to console
# (which Render captures) so real errors are actually diagnosable.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# -----------------------------------------------------------------
# TUTORO API CONFIG
# -----------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'lead_submit': '10/hour',
        'status_check': '20/hour',
        # Login is the one endpoint where an attacker gets direct
        # feedback on password guesses -- tighter than the read-only
        # scopes above, and keyed by IP (see LoginThrottle) so one
        # attacker can't lock out other users sharing the endpoint.
        'login': '10/hour',
        # OTP email verification (see apps.accounts.views) -- request
        # is tighter since each hit sends a real email; verify is a
        # touch looser since a genuine user might mistype a code once
        # or twice, but still capped well below brute-forcing a
        # 6-digit space.
        'otp_request': '5/hour',
        'otp_verify': '15/hour',
        # Phase 4 AI-layer scopes -- each hit here costs a real
        # Anthropic API call, so every AI-facing endpoint gets its own
        # scope rather than sharing the generic ones above.
        'generate_bio': '10/hour',   # Sonnet-backed, pricier than the rest
        'tutor_search': '60/hour',   # public browsing -- looser, most calls have no ?q= at all
        'faq_chat': '20/hour',       # public, anonymous -- IP-keyed via AnonRateThrottle
    },
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# -----------------------------------------------------------------
# DJANGO-AXES -- brute-force lockout for the Django admin login page.
# Scoped to admin only (AXES_ONLY_ADMIN_SITE) so it never touches
# /api/auth/login/, which already has its own throttle above; the two
# mechanisms are deliberately independent rather than layered, so a
# failed API login attempt never counts toward an admin lockout or
# vice versa.
# -----------------------------------------------------------------
AXES_ONLY_ADMIN_SITE = True
# Locked out after this many failures from the same combination of
# username + IP -- keyed on both (the axes default) so one attacker
# spraying passwords across many admin usernames from one IP is still
# caught, and so one legitimate admin's mistyped password doesn't lock
# out a different admin sharing an office IP.
AXES_FAILURE_LIMIT = 5
# Cooloff is a timedelta, not raw hours, in modern axes versions --
# short enough that a genuine admin isn't locked out for long, long
# enough to make scripted brute-forcing impractical at this scale.
AXES_COOLOFF_TIME = timedelta(minutes=30)
# A successful login clears the failure count for that username/IP
# pair, rather than making a lockout persist through a later success.
AXES_RESET_ON_SUCCESS = True

# -----------------------------------------------------------------
# EMAIL -- instant notification when a new lead comes in.
# Uses Gmail SMTP by default since it's genuinely free (an "app
# password" from your own Gmail account, not a paid service).
# If EMAIL_HOST_USER isn't set, notifications are silently skipped
# rather than breaking lead submission -- getting a lead saved always
# matters more than the notification about it.
# -----------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
ADMIN_NOTIFICATION_EMAIL = env('ADMIN_NOTIFICATION_EMAIL', default=EMAIL_HOST_USER)


# WHATSAPP -- instant staff notification when a new lead comes in, via
# Twilio's WhatsApp Business API. Same philosophy as EMAIL above: if
# these aren't set, apps.notifications.services.send_whatsapp_message
# silently no-ops rather than erroring, so lead submission itself can
# never break because WhatsApp isn't configured yet.
#
# TWILIO_WHATSAPP_FROM must be a Twilio-approved WhatsApp sender,
# formatted like 'whatsapp:+14155238886'. ADMIN_WHATSAPP_NUMBER is
# where staff notifications land, formatted like 'whatsapp:+91XXXXXXXXXX'.
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM = env('TWILIO_WHATSAPP_FROM', default='')
ADMIN_WHATSAPP_NUMBER = env('ADMIN_WHATSAPP_NUMBER', default='')

# -----------------------------------------------------------------
# ANTHROPIC API -- used by apps/ai (Phase 4: smart matching, bio
# generation, review moderation, FAQ chatbot). Never hardcode the key;
# it must come from the environment only. Left blank by default so
# local dev without a key still boots -- apps/ai checks for this and
# degrades gracefully (raises a clear error only when an AI feature is
# actually invoked, not at Django startup) rather than crashing the
# whole app for developers who aren't touching AI features yet.
# -----------------------------------------------------------------
ANTHROPIC_API_KEY = env('ANTHROPIC_API_KEY', default='')

# -----------------------------------------------------------------
# JAZZMIN ADMIN THEME
# -----------------------------------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Tutoro Admin",
    "site_header": "Tutoro",
    "site_brand": "Tutoro",
    "welcome_sign": "Welcome to Tutoro Admin",
    "copyright": "Tutoro",
    "search_model": ["leads.ParentLead", "leads.TutorLead"],
    "show_sidebar": True,
    "navigation_expanded": True,
    # Leads first -- this is what gets checked every single day.
    "order_with_respect_to": [
        "leads", "matching", "profiles", "accounts", "catalog",
        "reviews", "payments", "notifications", "audit",
    ],
    "icons": {
        "leads.ParentLead": "fas fa-child",
        "leads.TutorLead": "fas fa-chalkboard-teacher",
        "accounts.User": "fas fa-user-shield",
        "profiles.ParentProfile": "fas fa-users",
        "profiles.TutorProfile": "fas fa-graduation-cap",
        "catalog.Area": "fas fa-map-marker-alt",
        "catalog.Subject": "fas fa-book",
        "matching.StudentRequest": "fas fa-clipboard-list",
        "matching.Assignment": "fas fa-handshake",
        "reviews.Review": "fas fa-star",
    },
    "custom_css": None,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "navbar": "navbar-dark",
    "brand_colour": "navbar-dark",
    "accent": "accent-warning",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
