# Generated by Django 6.0.7 on 2026-07-11 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VERIFY', 'Verify'), ('REJECT', 'Reject'), ('MATCH', 'Match created'), ('LOGIN', 'Login')], max_length=10)),
                ('target_model', models.CharField(help_text="e.g. 'TutorProfile'", max_length=100)),
                ('target_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Extra context, e.g. {'old_status': 'PENDING', 'new_status': 'VERIFIED'}")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='audit_log_target__775c76_idx'), models.Index(fields=['actor', 'created_at'], name='audit_log_actor_i_2ba9f4_idx')],
            },
        ),
    ]
