# Generated by Django 6.0.7 on 2026-07-11 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(default='Telangana', max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Turn off instead of deleting when a city is paused.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'catalog_city',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic (school/college)'), ('COMPETITIVE', 'Competitive Exam (EAMCET, JEE, NEET…)'), ('SKILL', 'Skill-based (coding, music, etc.)')], default='ACADEMIC', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_subject',
                'indexes': [models.Index(fields=['category', 'is_active'], name='catalog_sub_categor_9bab29_idx')],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='catalog.city')),
            ],
            options={
                'verbose_name_plural': 'areas',
                'db_table': 'catalog_area',
                'indexes': [models.Index(fields=['city', 'is_active'], name='catalog_are_city_id_cdc7f6_idx')],
                'unique_together': {('city', 'slug')},
            },
        ),
    ]
