# Generated by Django 5.0.14 on 2026-08-04 07:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('classes_offered', models.CharField(blank=True, help_text="Comma-separated StudentClass codes, e.g. 'C1_5,C6_8,C9_10'.", max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919876543210' or '9876543210'.", regex='^\\+?91?\\d{10}$')])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('referral_terms', models.TextField(blank=True, help_text='Commission/referral agreement details, in plain language.')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Optional structured commission %, if the deal is a simple flat percentage.', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Turn off instead of deleting when a partnership pauses/ends.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas_covered', models.ManyToManyField(blank=True, help_text='Localities this academy serves or is reachable from.', related_name='academies', to='catalog.area')),
                ('subjects', models.ManyToManyField(blank=True, related_name='academies', to='catalog.subject')),
            ],
            options={
                'verbose_name_plural': 'academies',
                'db_table': 'catalog_academy',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='catalog_aca_is_acti_e443bf_idx')],
            },
        ),
    ]
